#!/bin/sh
username="\033[1m\033[95m$USER@$(uname -n)\033[1m\033[93m"
kernel="\033[1m\033[93m$(uname -s)$(uname -r)"
OS="$(cat /etc/*release | grep -i pretty_name | awk -F "=" '{print $2}' | sed 's/"//g')"
host="$(uname -m)"
processor="$(cat /proc/cpuinfo | grep 'model name' | uniq | cut -d' ' -f3-)"
memory="$(cat /proc/meminfo | grep 'MemTotal' | uniq | cut -d' ' -f3- | xargs)"
editor="$EDITOR"

info(){
	printf "\n$username\nKernel: $kernel\nOS: $OS\nHost: $host\nProcessor: $processor\nMemory: $memory\nEditor: $editor\n\033[40m  \033[41m  \033[42m  \033[43m  \033[44m  \033[45m  \033[46m  \033[47m  \033[0m"
}

ascii_0="    ⢀⣀⣤⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀"
ascii_1="  ⣠⣾⣿⣿⡿⠿⡿⠛⢻⡿⢉⠙⡅⠠⢼⣿⣿⣿⣆⠀⠀⠀⠀⠀"
ascii_2="⢀⣾⣿⣿⡅⠸⠣⠀⡇⢰⠀⣇⠘⠇⣠⠀⣾⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀"
ascii_3="⢸⣿⣿⣿⣷⠀⢠⡀⣰⣄⣠⣿⣶⡶⢿⡶⠛⢻⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀"
ascii_4="⠘⣿⣿⣿⣿⡷⠻⣿⠉⠟⢁⡈⢿⠀⡄⢡⠀⢻⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀"
ascii_5="⠀⢻⣿⣿⣿⣧⠀⠉⠀⢠⠘⠇⢸⡀⠁⣸⣄⣹⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀"
ascii_6="  ⠈⢿⣿⣿⣿⣆⣸⣦⣼⣷⣶⣿⣿⣿⣿⣿⡿⠟⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀"
ascii_7="    ⠀⠙⠿⢿⣿⣿⣿⣿⣿⠟⠛⠛⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
ascii_8="             ⠈⠻⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"


ascii(){
	printf "\033[1m\033[93m$ascii_0\n"
	printf "\033[1m\033[93m$ascii_1\n"
	printf "$ascii_2\n"
	printf "$ascii_3\n"
	printf "$ascii_4\n"
	printf "$ascii_5\n"
	printf "$ascii_6\n"
	printf "$ascii_7\n"
	printf "$ascii_8\n"
}

paste <(ascii) <(info)
